set(_CATKIN_CURRENT_PACKAGE "joy_tutorial")
set(joy_tutorial_VERSION "0.0.0")
set(joy_tutorial_MAINTAINER "human <human@todo.todo>")
set(joy_tutorial_PACKAGE_FORMAT "2")
set(joy_tutorial_BUILD_DEPENDS "roscpp" "std_msgs")
set(joy_tutorial_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(joy_tutorial_BUILDTOOL_DEPENDS "catkin")
set(joy_tutorial_BUILDTOOL_EXPORT_DEPENDS )
set(joy_tutorial_EXEC_DEPENDS "roscpp" "std_msgs")
set(joy_tutorial_RUN_DEPENDS "roscpp" "std_msgs")
set(joy_tutorial_TEST_DEPENDS )
set(joy_tutorial_DOC_DEPENDS )
set(joy_tutorial_URL_WEBSITE "")
set(joy_tutorial_URL_BUGTRACKER "")
set(joy_tutorial_URL_REPOSITORY "")
set(joy_tutorial_DEPRECATED "")