TrajectoryPlannerROS:
  max_vel_x: 0.1
  min_vel_x: 0.05
  max_vel_theta: 0.05
  min_in_place_vel_theta: 0.005

  acc_lim_theta: 1.5
  acc_lim_x: 1
  acc_lim_y: 1

  holonomic_robot: true
  meter_scoring: true
