DWAPlannerROS:
  # max_vel_x: 0.5
  # min_vel_x: 0.15
  max_vel_theta: 0.2
  min_in_place_vel_theta: 0.1

  # acc_lim_theta: 0.05
  # acc_lim_x: 0.2
  # acc_lim_y: 0.2

  # holonomic_robot: true
  # meter_scoring: true


  max_rot_vel: 0.2
  min_rot_vel: 0.01
  # occdist_scale: 0.02
