global_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 5.0
  static_map: true
  rolling_window: false
  track_unknown_space: true

  plugins:
      - {name: static_layer,          type: "costmap_2d::StaticLayer"}
      - {name: obstacle_layer_kinect, type: "costmap_2d::VoxelLayer"}
      - {name: inflation_layer,       type: "costmap_2d::InflationLayer"}


  obstacle_layer_kinect:
    # observation_sources: kinect_laserscan kinect_laserscan_shortRange kinect_laserscan_longRange
    # observation_sources: kinect_laserscan_shortRange kinect_laserscan_longRange
    observation_sources: kinect_laserscan
    kinect_laserscan: {sensor_frame: camera_link, data_type: LaserScan, topic: kinect_scan, marking: true, clearing: true, obstacle_range: 3.0, raytrace_range: 6.5, inf_is_valid: true}
    # kinect_laserscan_shortRange: {sensor_frame: camera_link, data_type: LaserScan, topic: kinect_scan_shortRange, marking: true, clearing: false, obstacle_range: 3.0, raytrace_range: 6.5, inf_is_valid: false}
    # kinect_laserscan_longRange: {sensor_frame: camera_link, data_type: LaserScan, topic: kinect_scan_longRange, marking: true, clearing: true, obstacle_range: 3.0, raytrace_range: 6.5, inf_is_valid: false}
    # kinect: {sensor_frame: camera_link, data_type: PointCloud2, topic: camera/depth_registered/points, marking: true, clearing: true, inf_is_valid: true}

  inflation_layer:
    cost_scaling_factor: 4.0
    inflation_radius: 0.15


  static_layer:
    enabled: true
