local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 3.0
  publish_frequency: 3.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05
  max_obstacle_height: 1.5

  plugins:
      - {name: obstacle_layer_kinect, type: "costmap_2d::VoxelLayer"}
      - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  obstacle_layer_kinect:
    observation_sources: kinect_laserscan kinect_laserscan_shortRange kinect kinect_laserscan_longRange
    kinect_laserscan: {sensor_frame: camera_link, data_type: LaserScan, topic: kinect_scan, marking: true, clearing: true, obstacle_range: 9.0, raytrace_range: 9.5, inf_is_valid: false}
    kinect_laserscan_shortRange: {sensor_frame: camera_link, data_type: LaserScan, topic: kinect_scan_shortRange, marking: true, clearing: true, obstacle_range: 9.0, raytrace_range: 9.5, inf_is_valid: false}
    kinect_laserscan_longRange: {sensor_frame: camera_link, data_type: LaserScan, topic: kinect_scan_longRange, marking: true, clearing: true, obstacle_range: 9.0, raytrace_range: 9.5, inf_is_valid: false}
    kinect: {sensor_frame: camera_link, data_type: PointCloud2, topic: camera/depth_registered/points, marking: true, clearing: true, min_obstacle_height: 0.65,max_obstacle_height: 1.45}

  inflation_layer:
    inflation_radius: 0.2
