recovery_behaviors:
  - name: 'super_conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'rotate_recovery_1'
    type: 'rotate_recovery/RotateRecovery'
  - name: 'rotate_recovery_2'
    type: 'rotate_recovery/RotateRecovery'
  - name: 'rotate_recovery_3'
    type: 'rotate_recovery/RotateRecovery'

super_conservative_reset:
  reset_distance: 3.0

conservative_reset:
  reset_distance: 2.0

aggressive_reset:
  reset_distance: 1.0

rotate_recovery_1:
  sim_granularity: 0.017
  max_vel_theta: 0.2
  min_in_place_vel_theta: 0.1

rotate_recovery_2:
  sim_granularity: 0.017
  max_vel_theta: 0.2
  min_in_place_vel_theta: 0.1

rotate_recovery_3:
  sim_granularity: 0.017
  max_vel_theta: 0.2
  min_in_place_vel_theta: 0.1
